eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19041/eureka/

server:
  port: 19061

spring:
  application:
    name: service-zuul

zuul:
  routes:
    feignA:
      path: /datacenter/**
      serviceId: service-feign